name: publish
on: [push]
jobs:
publish-hello-docker-image:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
- name: Build the hello-docker Docker image
run: |
       docker build . --tag ghcr.io/RinaldyD/order-service-image:latest
       docker run ghcr.io/RinaldyD/order-service-image:latest
       docker push ghcr.io/RinaldyD/order-service-image:latest
